# Generated by Django 6.0.6 on 2026-06-14 07:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('slug', models.SlugField(editable=False, max_length=220, unique=True, verbose_name='slug')),
                ('prompt', models.TextField(blank=True, verbose_name='consigna inicial')),
                ('visibility', models.CharField(choices=[('tail', 'Solo el final del fragmento anterior'), ('full', 'El último fragmento completo')], default='tail', max_length=10, verbose_name='visibilidad')),
                ('tail_words', models.PositiveIntegerField(default=5, help_text='Cuántas palabras del final se muestran (solo si la visibilidad es «solo el final»).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='palabras visibles del final')),
                ('max_fragments', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(2)], verbose_name='número máximo de fragmentos')),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada')], default='open', max_length=10, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_stories', to=settings.AUTH_USER_MODEL, verbose_name='creador')),
            ],
            options={
                'verbose_name': 'historia',
                'verbose_name_plural': 'historias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='texto')),
                ('order', models.PositiveIntegerField(verbose_name='orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='corpse.story', verbose_name='historia')),
            ],
            options={
                'verbose_name': 'fragmento',
                'verbose_name_plural': 'fragmentos',
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('story', 'order'), name='unique_fragment_order_per_story')],
            },
        ),
    ]
