# Generated by Django 6.0.6 on 2026-06-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('author', models.CharField(max_length=150, verbose_name='autor')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicada')], default='draft', max_length=10, verbose_name='estado')),
                ('body', models.TextField(blank=True, verbose_name='contenido')),
                ('slug', models.SlugField(editable=False, max_length=220, unique=True, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
            ],
            options={
                'verbose_name': 'historia',
                'verbose_name_plural': 'historias',
                'ordering': ['-created_at'],
            },
        ),
    ]
